"""Add reserved_by and reserved_until to seats

Revision ID: 0001_add_seat_reserved_fields
Revises: 
Create Date: 2026-02-18 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_add_seat_reserved_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('reserved_by', sa.String(length=36), nullable=True))
    op.add_column('seats', sa.Column('reserved_until', sa.DateTime(), nullable=True))
    # Create foreign key to users table
    op.create_foreign_key('fk_seats_reserved_by_users', 'seats', 'users', ['reserved_by'], ['id'])
    # Create index on reserved_until
    op.create_index('ix_seats_reserved_until', 'seats', ['reserved_until'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seats_reserved_until', table_name='seats')
    op.drop_constraint('fk_seats_reserved_by_users', 'seats', type_='foreignkey')
    op.drop_column('seats', 'reserved_until')
    op.drop_column('seats', 'reserved_by')
    # ### end Alembic commands ###
