import { configureStore } from '@reduxjs/toolkit';
import authReducer from './slices/authSlice';





























































































































































































































































































































































- Ensure events have proper data populated- Check if autocomplete endpoint is responding- Verify query is at least 2 characters### Suggestions Not Appearing- Consider implementing caching- Verify query parameters are optimized- Check database indexes### Slow Search Performance- Ensure event data is properly indexed- Check if filters are too restrictive- Verify event status is "PUBLISHED"### Search Returns No Results## Troubleshooting8. **Image Search** - Search events by event poster/image7. **Voice Search** - Speech-to-text search capability6. **Search URL Sharing** - Share filters via shareable URLs5. **Social Sharing** - Share search results with friends4. **Personalized Search Filters** - User-specific default filters3. **Search Analytics Dashboard** - Most searched queries, trending categories2. **ML-based Recommendations** - "Recommended for you" based on search history1. **Full-text Search Engine Integration** (Elasticsearch, Solr)## Future Enhancements- Rate limiting on search endpoints (configurable)- Sensitive data filtered from suggestions- Distance calculations use safe Haversine formula- Query parameter validation (SQL injection prevention)## Security Features- localStorage for recent searches and saved filters- Lazy loading of search results- Debounced search input (300ms)### Frontend Optimization- Connection pooling for multiple concurrent searches- Indexed columns for filter queries- Pagination limits result sets### Database Optimization- Trending searches updated every 24 hours- Suggestions cached for 1 hour- Search results cached for 5 minutes per query### Caching Strategy## Performance Considerations- **Geolocation:** Latitude/longitude fields for distance calculations- **Full-text search:** Tags and title are indexed for faster searching- **Indexes:** Composite indexes on (category, status), (location, status), (start_date, status)### Search Optimization- `view_count` (int): Track popularity- `tags` (string): Comma-separated tags for categorization- `featured` (boolean): Mark as featured eventThe Event model now includes:### Event Model Extensions## Database Schema```};  }    dispatch(getSearchSuggestions(query));  if (query.length >= 2) {const handleSuggestions = (query) => {import { getSearchSuggestions } from '../redux/slices/searchSlice';```javascript### Getting Suggestions```};  }));    limit: 20    page: 1,    sortBy: 'date',    priceMax: 500,    priceMin: 50,    endDate: '2024-03-31',    startDate: '2024-03-01',    location: 'New York',    category: 'music',    search: 'concert',  dispatch(searchEvents({const handleAdvancedSearch = () => {```javascript### Advanced Filtering```};  );    // JSX  return (  };    }));      limit: 20      page: 1,      search: query,    dispatch(searchEvents({  const handleSearch = (query) => {  const { results, loading } = useSelector(state => state.search);  const dispatch = useDispatch();const MyComponent = () => {import { searchEvents } from '../redux/slices/searchSlice';import { useDispatch, useSelector } from 'react-redux';```javascript### Basic Search## Usage Examples```}  recentSearches: []    // Recent search history  page: 1,              // Current page  totalResults: 0,      // Total count of results  currentFilters: {},   // Current applied filters  error: null,          // Error message  loading: false,        // Loading state  suggestions: [],       // Array of autocomplete suggestions  results: [],           // Array of event results{```javascript**State:**- `clearResults()` - Clear search results- `clearRecentSearches()` - Clear search history- `addRecentSearch(search)` - Add search to recent history- `getSearchSuggestions(query)` - Async thunk to get suggestions- `searchEvents(filters)` - Async thunk to search events**Actions:**Location: `frontend/src/redux/slices/searchSlice.js`### Search Slice## Redux State Management```/search?q=query&category=music&location=New York```**Route:**- Empty state messaging- Loading and error states- Event cards with details- Results display in grid layout- Integrated search interface**Features:**Location: `frontend/src/pages/SearchPage.jsx`### SearchPage Component```}} />  // Handle search with filters<AdvancedSearch onSearch={(filters) => {```javascript**Props:**- Recent searches display- Saved searches management- Price range sliders- Multi-select filters- Collapsible filter panel- Search bar with autocomplete**Features:**Location: `frontend/src/components/AdvancedSearch.jsx`### AdvancedSearch Component## Frontend Components```}  }    "pages": 13    "total": 245,    "limit": 20,    "page": 1,  "pagination": {  ],    }      "featured": true      "image_url": "...",      "start_date": "2024-03-15T19:00:00Z",      "location": "New York, NY",      "category": "music",      "description": "...",      "title": "Concert Title",      "id": 123,    {  "events": [{```json**Response:**```GET /api/events?search=concert&category=music&location=New York&startDate=2024-03-01&priceMin=50&priceMax=500&sortBy=date&page=1&limit=20```**Example Request:**- `limit` (int): Results per page- `page` (int): Page number for pagination- `sortBy` (string): Sort order - `date`, `price`, `popularity`- `featured` (boolean): Show only featured events- `tags` (string): Comma-separated tags to filter- `priceMax` (float): Maximum ticket price- `priceMin` (float): Minimum ticket price- `endDate` (ISO8601): Filter events ending before this date- `startDate` (ISO8601): Filter events starting after this date- `location` (string): Filter by location (substring match)- `category` (string): Filter by event category- `search` (string): Search query across event title, description, tags**Query Parameters:**List events with advanced filtering.#### `GET /api/events` (Enhanced)### Enhanced Event Listing```}  }    "max": 10000    "min": 0,  "price_range": {  "locations": ["New York", "Los Angeles", "Chicago", ...],  "categories": ["music", "sports", "technology", "entertainment"],{```json**Response:**Get available filter options for building dynamic filter UI.#### `GET /api/search/filters````}  ]    }      "start_date": "2024-03-15T19:00:00Z"      "distance_km": 2.5,      "location": "New York, NY",      "title": "Concert at Madison Square Garden",      "id": 123,    {  "events": [{```json**Response:**- `radius` (float, optional, default=50): Search radius in kilometers- `lng` (float, required): Longitude- `lat` (float, required): Latitude**Parameters:**Find events near a geographic location.#### `GET /api/search/nearby````}  ]    }      "count": 189      "category": "sports",    {    },      "count": 245      "category": "music",    {  "trending": [{```json**Response:**Get trending search topics and popular categories.#### `GET /api/search/trending````}  ]    }      "id": 456      "title": "Live Nation Entertainment",      "type": "organizer",    {    },      "category": "music"      "id": 123,      "title": "Taylor Swift Eras Tour",      "type": "event",    {  "suggestions": [{```json**Response:**- `q` (string, required): Search query (minimum 2 characters)**Parameters:**Get autocomplete suggestions for search queries.#### `GET /api/search/suggestions`### Search Endpoints## API Endpoints- Real-time suggestion updates- Category suggestions- Organizer name suggestions- Autocomplete event names### 4. **Smart Suggestions**- Location-aware results- Radius-based filtering- Distance calculation (Haversine formula)- Find nearby events (geolocation support)### 3. **Location-Based Features**- One-click search replication- Quick access to saved searches- Save frequently used search filters- Automatic search history (localStorage)### 2. **Search History & Saved Searches**- Featured events highlighting- Sort by (date, price, popularity)- Tag-based filtering- Price range filtering- Date range filtering- Location-based search- Category-based filtering- Real-time search suggestions- Multi-criteria search bar with autocomplete### 1. **Advanced Search Component**## FeaturesThe ticket-master application now features a comprehensive search and filtering system that rivals major ticketing platforms like Ticketmaster. Users can discover events through multiple search methods with powerful filtering capabilities.## Overviewimport eventsReducer from './slices/eventsSlice';
import ticketsReducer from './slices/ticketsSlice';
import paymentsReducer from './slices/paymentsSlice';
import uiReducer from './slices/uiSlice';
import searchReducer from './slices/searchSlice';
import selectedSeatsReducer from './slices/selectedSeatsSlice';

const store = configureStore({
  reducer: {
    auth: authReducer,
    events: eventsReducer,
    tickets: ticketsReducer,
    payments: paymentsReducer,
    ui: uiReducer,
    search: searchReducer,
    selectedSeats: selectedSeatsReducer,
  },
});

export default store;
